### ISSUE TITLE
关于挂在数据集要小于100M的问题

### ISSUE THREAD

**Issue by Gu-xiaobai** [RussellCloud/russell-docs#7]
Total size: 215.6MiB. Code size too large to sync, please keep it under 100MB.If you have data files in the current directory, please upload them separately using "russell data" command and remove them from here.
请问这个问题如何解决？难道挂载的数据集大于100M 就得分开上传，然后同时挂载？这太不方便了吧

**Comment by hongxin001** [comment]
你好，数据集是单独存储的，不能放在代码目录下上传，代码的大小一般不会超过100MB，你可以查看文档看如何上传并在任务中使用数据集，具体限制是20G
