### ISSUE TITLE
russell cloud登录问题

### ISSUE THREAD

**Issue by Fortressll** [RussellCloud/russell-docs#8]
Windows登陆时无法在终端中粘贴token，是我操作不对吗，右键也没反应。

**Comment by zxuu** [comment]
默认隐藏显示吧

**Comment by hongxin001** [comment]
token是不会显示出来的，另外windows终端下有时候不能通过右键或者快捷键粘贴，可以使用左上角的图标中的编辑下的粘贴按钮，这是windows本身的问题

**Comment by Fortressll** [comment]
好的，问题已解决，非常感谢，真心祝愿你们的平台越来越好




------------------ 原始邮件 ------------------
发件人: "Owen"<notifications@github.com>;
发送时间: 2018年10月19日(星期五) 下午2:20
收件人: "RussellCloud/russell-docs"<russell-docs@noreply.github.com>;
抄送: "185241531"<185241531@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [RussellCloud/russell-docs] russell cloud登录问题 (#8)




token是不会显示出来的，另外windows终端下有时候不能通过右键或者快捷键粘贴，可以使用左上角的图标中的编辑下的粘贴按钮，这是windows本身的问题

**Comment by hongxin001** [comment]
谢谢！
