### ISSUE TITLE
图片效果

### ISSUE THREAD

**Issue by zxuu** [RussellCloud/russell-docs#9]
![result](https://user-images.githubusercontent.com/33821934/47199058-30b2ff80-d3a2-11e8-88cd-fdbbaea3cab2.png)
![result](https://user-images.githubusercontent.com/33821934/47199071-3c9ec180-d3a2-11e8-95e3-571588ea445f.png)
为什么在云端处理的效果不好？？

**Comment by hongxin001** [comment]
这个是模型本身的参数问题

**Comment by hongxin001** [comment]
训练更多轮就可以获得更好的效果

**Comment by hongxin001** [comment]
示例只是为了演示流程，所以没有增加训练轮数
